include:
  - path: './db/compose.yaml'

services:
  backend:
    build:
      dockerfile: backend.dockerFile
      context: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://127.0.0.1:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgreSQL
    depends_on:
      - redis
      - postgreSQL
    networks:
      - semd-shared-network
    
  # mlflow:
  #   build:
  #     dockerfile: mlflow.dockerFile
  #     context: ../ai/mlflow/
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - semd-shared-network

networks:
  semd-shared-network:
    name: semd-shared-network
    driver: bridge
    external: false