services:
  postgreSQL:
    image: docker.io/library/postgres:17
    restart: always
    container_name: semd-database
    env_file:
      - ./postgres.env
    volumes:
      - semd_postgresql_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    networks:
      - semd-shared-network

  redis:
    container_name: semd-redis
    build:
      context: ..
      dockerfile: docker/redis.Dockerfile
    volumes:
      - semd_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - semd-shared-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # backend:
  #   build:
  #     context: ..
  #     dockerfile: docker/backend.Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     MLFLOW_TRACKING_URI: http://127.0.0.1:5000
  #     REDIS_HOST: ${REDIS_HOST:-redis}
  #     REDIS_PORT: ${REDIS_PORT:-6379}
  #     REDIS_PASSWORD: ${REDIS_PASSWORD:-}
  #     REDIS_DB: ${REDIS_DB:-0}
  #     POSTGRES_HOST: ${POSTGRES_HOST:-postgreSQL}
  #   depends_on:
  #     - postgreSQL
  #     - redis
  #   networks:
  #     - semd-shared-network

volumes:
  semd_postgresql_data:
  semd_redis_data:

networks:
  semd-shared-network:
    name: semd-shared-network
    driver: bridge
    external: false
