services:
  postgreSQL:
    image: docker.io/library/postgres:latest
    restart: always
    container_name: semd-database
    volumes:
      - semd_postgresql_data:/var/lib/postgresql
      - ./semd.db.sql:/docker-entrypoint-initdb.d/init.sql:Z
    ports:
      - 5433:5432
    env_file:
      - .env
    networks:
      - semd-shared-network
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  redis:
    container_name: semd-redis
    build:
      dockerfile: database/redis.dockerFile
      context: ..
    volumes:
      - semd_redis_data:/data
    ports:
      - 6379:6379
    networks:
      - semd-shared-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  semd_postgresql_data:
  semd_redis_data:

networks:
  semd-shared-network:
    name: semd-shared-network
    driver: bridge
    external: false